-- 코드를 입력하세요
# SELECT A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, B.REVIEW_SCORE
# FROM REST_INFO AS A 
#     RIGHT JOIN 
#         REST_REVIEW AS B 
#     ON A.REST_ID = B.REST_ID 


SELECT 
    A.REST_ID, A.REST_NAME, A.FOOD_TYPE, A.FAVORITES, A.ADDRESS, 
    ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
FROM REST_INFO AS A 
    RIGHT JOIN 
        REST_REVIEW AS B 
    ON A.REST_ID = B.REST_ID 
WHERE SUBSTRING_INDEX(ADDRESS, ' ', 1)='서울특별시' OR SUBSTRING_INDEX(ADDRESS, ' ', 1)='서울시'
GROUP BY REST_ID 
ORDER BY SCORE DESC, A.FAVORITES DESC
